version: '3.8'

services:
  nats:
    image: nats
    command: -js
    ports:
      - "4222:4222"
      - "8222:8222"
    networks:
      - app_network
    restart: unless-stopped

  grpc_server:
    build:
      context: .
      dockerfile: build/server/Dockerfile
    image: telegram-grpc-service-server
    depends_on:
      - nats
    environment:
      TELEGRAM_BOT_TOKEN: ${BOT_TOKEN}
    ports:
      - "50051:50051"
    networks:
      - app_network
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: build/worker/Dockerfile
    image: telegram-grpc-service-worker
    depends_on:
      - nats
    environment:
      TELEGRAM_BOT_TOKEN: ${BOT_TOKEN}
    networks:
      - app_network
    restart: unless-stopped

  gateway:
    build:
      context: .
      dockerfile: build/gateway/Dockerfile
    image: telegram-grpc-service-gateway
    depends_on:
      - grpc_server
    environment:
      GRPC_SERVER_ENDPOINT: grpc_server:50051
    ports:
      - "8080:8080"
    networks:
      - app_network
    restart: unless-stopped

  swagger_ui:
    image: swaggerapi/swagger-ui
    depends_on:
      - gateway
    ports:
      - "8081:8080"
    environment:
      SWAGGER_JSON: /foo/messaging.swagger.json
    volumes:
      - ./gen/swagger:/foo
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    driver: bridge
