version: '3.8'

services:
  nats-server:
    image: nats:latest
    command: ["-js"]
    network_mode: host

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - nats-server
    network_mode: host

  swagger-ui:
    image: swaggerapi/swagger-ui
    environment:
      SWAGGER_JSON: /swagger/gen/swagger/messaging.swagger.json  # Путь к вашему файлу Swagger JSON
    ports:
      - "8081:8080"  # Swagger UI будет доступен на порту 8081
    volumes:
      - ./gen/swagger:/swagger/gen/swagger  # Монтируем директорию с Swagger JSON
    depends_on:
      - app
    networks:
      - my_custom_network

networks:
  my_custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
